version: '3'

services:
  PostgreSQLAdmin:
    container_name: postgres_db
    restart: always
    image: postgres:11.6-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rick_and_morty